org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
systemProp.net.minecraftforge.gradle.check.certs=false

minecraft_version=1.20.1

minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.10

forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=official

mapping_version=1.20.1

mod_id=lastpraiseofmaggot

mod_name=Last Praise of Maggot (\u843d\u5e55\u533a)

mod_license=Apache-2.0 license

mod_version=1.0.0

mod_group_id=com.ovo.lastpraiseofmaggot

mod_authors=OvO 

mod_description=Brother Maggot and Sister Maggot, an addon for Last Song of Elysian.

curios_version=5.2.0+1.20.1


main_mod_version=1.0.0
